### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by S0utheast** [Rakeshmonkee/DMA#1]
First of all thank you for the tutorial and secondly allow me to ask questions, please forgive me for being just a newbie!
is that right? But if I change these two values to 80, I can't do a speed test.

  parameter [7:0]   HEADER_TYPE = 8'h80,
  parameter [7:0]   CAPABILITIES_PTR = 8'h80,

**Comment by Rakeshmonkee** [comment]
Hi, thanks for your comment.

Thank you for reminding me of this. 

I have noted down in the guide that once you set these 2 values to 80, it breaks the config space. What I forgot to mention is that this only works for primarily MSI mother boards on main PC. If you have a MSI mother board, lmk and I can help you troubleshoot the problem, but otherwise your motherboard doesn't like the config space breaking itself, and I suggest you get an MSI motherboard for any other FW you create and or buy.

I will also add this to the guide for anyone who has a similar issue.

Thank you again for your issue

**Comment by S0utheast** [comment]
> 嗨，感谢您的评论。
> 
> 谢谢你提醒我这一点。
> 
> 我在指南中指出，一旦您将这 2 个值设置为 80，它就会破坏配置空间。我忘了提到的是，这仅适用于主 PC 上的主要 MSI 主板。如果你有一个微星主板，lmk和我可以帮助你解决问题，但除此之外，你的主板不喜欢配置空间自行中断，我建议你为你创建和/或购买的任何其他固件买一个微星主板。
> 
> 我还会将其添加到指南中，供任何有类似问题的人使用。
> 
> 再次感谢您的问题

I am the MSI motherboard, b560 wifi motherboard

**Comment by S0utheast** [comment]
> > > 嗨，感谢您的评论。
> > 
> > 
> > > 
> > 
> > 
> > > 谢谢你提醒我这一点。
> > 
> > 
> > > 
> > 
> > 
> > > 我在指南中指出，一旦您将这 2 个值设置为 80，它就会破坏配置空间。我忘了提到的是，这仅适用于主 PC 上的主要 MSI 主板。如果你有一个微星主板，lmk和我可以帮助你解决问题，但除此之外，你的主板不喜欢配置空间自行中断，我建议你为你创建和/或购买的任何其他固件买一个微星主板。
> > 
> > 
> > > 
> > 
> > 
> > > 我还会将其添加到指南中，供任何有类似问题的人使用。
> > 
> > 
> > > 
> > 
> > 
> > > 再次感谢您的问题
> > 
> > 
> > 我是微星主板，b560 wifi主板
> 
> 你介意告诉我你对你的IP核做了哪些定制吗？
https://github.com/Silverr12/DMA-CFW-Guide?tab=readme-ov-file

I followed the tutorial exactly, before I changed it to 80 it was working and I could test properly, but after I changed it I couldn't test.

**Comment by Rakeshmonkee** [comment]
> > > > 嗨，感谢您的评论。
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 谢谢你提醒我这一点。
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 我在指南中指出，一旦您将这 2 个值设置为 80，它就会破坏配置空间。我忘了提到的是，这仅适用于主 PC 上的主要 MSI 主板。如果你有一个微星主板，lmk和我可以帮助你解决问题，但除此之外，你的主板不喜欢配置空间自行中断，我建议你为你创建和/或购买的任何其他固件买一个微星主板。
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 我还会将其添加到指南中，供任何有类似问题的人使用。
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 再次感谢您的问题
> 
> > > 
> 
> > > 
> 
> > > 我是微星主板，b560 wifi主板
> 
> > 
> 
> > 你介意告诉我你对你的IP核做了哪些定制吗？
> 
> https://github.com/Silverr12/DMA-CFW-Guide?tab=readme-ov-file
> 
> 
> 
> I followed the tutorial exactly, before I changed it to 80 it was working and I could test properly, but after I changed it I couldn't test.

Can you tell me the exact values you have changed, and just making sure, you went and edited the bus master flag and master abort flag to 1 from 0?

**Comment by S0utheast** [comment]
The vast majority of the data I didn't modify, I just modified some simple things like rw20 and rw21 =1 and dsn 
and then just modified parameter [7:0] HEADER_TYPE = 8'h80,
parameter [7:0] CAPABILITIES_PTR = 8'h80, and
Mainly to test this method of yours, so I didn't modify it too much, but the generated firmware is not available for speed testing

**Comment by Rakeshmonkee** [comment]
There could be a couple of reasons why you are experiencing this error,

1. You are not restarting your main PC after you flash
2. You don't have the right drivers installed on your second computer


If you are still having errors, please add me on discord: rakeshmonkee
