### ISSUE TITLE
Where are the .py files?

### ISSUE THREAD

**Issue by kweatherman** [Rakeshmonkee/DMA#2]
Where are the .py files mentioned in the readme.me?

**Comment by Rakeshmonkee** [comment]
you want them?

**Comment by Rakeshmonkee** [comment]
> Where are the .py files mentioned in the readme.me?

i have uploaded 2 of the files. the 3rd one, I am rewriting, because i am not happy with the first way i wrote it

**Comment by kweatherman** [comment]
Sure thanks either way. I was curious to see what they were. 
💡 I'll see your script and raise you one!
Here is one I wrote to convert Telescan PE .tlscan to .coe files.
Feel free to add it to your repo if you like.

It groups the DWORDs the same way as "pcileech_cfgspace.coe", but I was thinking of of breaking them down in smaller DWORD groups to make it easier to manually edit. I pretty much gave up on doing customizations this way. I think it will eventually take making the pcicleech gateware to not use the Vivado PCIe IP. And replace it with a custom/open-source one that completely ignores the config space (other than BAR setting which might be a requirement). Then one could put anything for a config space and have it not matter.

[telescan_to_coe.zip](https://github.com/Rakeshmonkee/DMA/files/14505478/telescan_to_coe.zip)

**Comment by Rakeshmonkee** [comment]
> Sure thanks either way. I was curious to see what they were. 
> 
> 💡 I'll see your script and raise you one!
> 
> Here is one I wrote to convert Telescan PE .tlscan to .coe files.
> 
> Feel free to add it to your repo if you like.
> 
> 
> 
> It groups the DWORDs the same way as "pcileech_cfgspace.coe", but I was thinking of of breaking them down in smaller DWORD groups to make it easier to manually edit. I pretty much gave up on doing customizations this way. I think it will eventually take making the pcicleech gateware to not use the Vivado PCIe IP. And replace it with a custom/open-source one that completely ignores the config space (other than BAR setting which might be a requirement). Then one could put anything for a config space and have it not matter (probably).
> 
> 
> 
> [telescan_to_coe.zip](https://github.com/Rakeshmonkee/DMA/files/14505478/telescan_to_coe.zip)
> 
> 
Good stuff man. I'll definitely have a look at this when I have the time ❤️
