### ISSUE TITLE
Zadig, DMA flashing

### ISSUE THREAD

**Issue by N4te2k** [Rakeshmonkee/DMA#4]
Hi, 
I am quite new to the DMA scene and recently came across your github guide for DMA firmwares and flashing FPGA device. 

When i open zadig on 2nd pc with jtag connected i do not see "RS232 +HS(Interface 0)" device. 

For me in Zadig it is looking like that: https://imgur.com/1Gr31lP

Which of those should i choose? or is there any fix for it to show up as "RS232 +HS(Interface 0)" device?

**Comment by Rakeshmonkee** [comment]
sorry for responding late,

this issue you are facing can depend on the DMA board you have. if you are using a DMA board from like HackDMA, Immortal, or a few other brands, they have their own tools for flashing since they are shit DMA board manufacturers.

Any DMA manufacturer that locks their board is SHIT

**Comment by N4te2k** [comment]
I am using Enigma Leetdma v1.2. So if thats case there is no way in flashing cfw?

**Comment by Rakeshmonkee** [comment]
> I am using Enigma Leetdma v1.2. Guess i gotta reach out to them then.

Yeah, you might need to reach out to them and use a flashing tool if their board is locked. I only have knowledge of using an FTD chip (rs232) which is accessible through zadig for my 35T (captain DMA squirrel)

**Comment by N4te2k** [comment]
Well thats what they advertise on their website: 
User Friendly
With the On-Board JTAG you can flash the LeetDMA board easily with just an USB connection from the Update Port. You are not forced to use complicated JTAG cables.

Flashing
OpenOCD can be used to easily flash your own firmware to the device.

I will reach out to them and post update here.

**Comment by Rakeshmonkee** [comment]
yeah, they all say "user-friendly / OpenOCD can be used to flash your firmware to the device easily" but when it comes to flashing, you will end up using OpenOCD, but will come in a tool they provide. Probably a CH347 chip that is on your board, which, you can use OpenOCD with, but you need to change values and stuff around in files and stuff

**Comment by N4te2k** [comment]
So quick update:
I managed to flash my cfw on the leetdma v1.2 with tips from @chuckwoolery.

- make sure u have ch341par driver installed https://www.wch-ic.com/downloads/CH341PAR_ZIP.html
- reboot may be required after install
- make sure you are connected to jtag, if successfull installed you should see ch347 under the com port you connected the jtag cable https://imgur.com/a/6QUooNM
- then for flashing you could either use this modified openocd version https://github.com/WCHSoftGroup/ch347 or ask in my case leetdma dupport to hand you their flashing tool which looks like that https://imgur.com/L0HxT28
- select your fw file to flash
- start the process and wait for it to finish
- reboot

**Comment by Rakeshmonkee** [comment]
thanks, ill have a look at this
