### ISSUE TITLE
Hello, may I ask if this program can bypass Valorant and China at the moment

### ISSUE THREAD

**Issue by xdx666666** [Rakeshmonkee/DMA#5]
I'm sorry to bother you, I'm a Chinese gamer, and now I want to buy DMA, but I'm poor, and I can't buy those expensive firmware, I would like to ask if your open source can bypass Valorant in China

**Comment by Rakeshmonkee** [comment]
> I'm sorry to bother you, I'm a Chinese gamer, and now I want to buy DMA, but I'm poor, and I can't buy those expensive firmware, I would like to ask if your open source can bypass Valorant in China

No, you need to find a bypass

**Comment by xdx666666** [comment]
@Rakeshmonkee Excuse me, can you elaborate on that?
